// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9SdgTipehmQ7HJa02Hu_DjpFzxOAq3_Y',
    appId: '1:1092180028360:web:4128aaf04411d3d1a4eefd',
    messagingSenderId: '1092180028360',
    projectId: 'turbo-de3d0',
    authDomain: 'turbo-de3d0.firebaseapp.com',
    databaseURL: 'https://turbo-de3d0-default-rtdb.firebaseio.com',
    storageBucket: 'turbo-de3d0.firebasestorage.app',
    measurementId: 'G-59K3LNGJBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx4Q-VOD7WsO20VU80oAi5XMMXdzYPESM',
    appId: '1:1092180028360:android:3b60c9d7a16521d1a4eefd',
    messagingSenderId: '1092180028360',
    projectId: 'turbo-de3d0',
    databaseURL: 'https://turbo-de3d0-default-rtdb.firebaseio.com',
    storageBucket: 'turbo-de3d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy30T4b8FeshjgC0PUdaoxNyx8O2sAyno',
    appId: '1:1092180028360:ios:4f7b27a8fa857413a4eefd',
    messagingSenderId: '1092180028360',
    projectId: 'turbo-de3d0',
    databaseURL: 'https://turbo-de3d0-default-rtdb.firebaseio.com',
    storageBucket: 'turbo-de3d0.firebasestorage.app',
    iosBundleId: 'com.example.turbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy30T4b8FeshjgC0PUdaoxNyx8O2sAyno',
    appId: '1:1092180028360:ios:4f7b27a8fa857413a4eefd',
    messagingSenderId: '1092180028360',
    projectId: 'turbo-de3d0',
    databaseURL: 'https://turbo-de3d0-default-rtdb.firebaseio.com',
    storageBucket: 'turbo-de3d0.firebasestorage.app',
    iosBundleId: 'com.example.turbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9SdgTipehmQ7HJa02Hu_DjpFzxOAq3_Y',
    appId: '1:1092180028360:web:77eea011f0fd7860a4eefd',
    messagingSenderId: '1092180028360',
    projectId: 'turbo-de3d0',
    authDomain: 'turbo-de3d0.firebaseapp.com',
    databaseURL: 'https://turbo-de3d0-default-rtdb.firebaseio.com',
    storageBucket: 'turbo-de3d0.firebasestorage.app',
    measurementId: 'G-C9ZP4DXPCT',
  );
}
